### ISSUE TITLE
test: hello-pepr-finalize failing 

### ISSUE THREAD

**Issue by schaeferka** [defenseunicorns/pepr-excellent-examples#182]
`hello-pepr-finalize` is failing. The failures are consistent, with logs similar to:

```
     `{"level":20,"time":1730134554180,"pid":17,"hostname":"pepr-6b7cfad2-722b-47f8-99ed-f3cbf65ab5b1-85ccd998b8-9rk6p","msg":"Ignoring Admission Callback: Binding defines name 'cm-watch-delete' but Object carries 'cm-watch-createorupdate'."}`,
      ... 767 more items
    ]

      at sift (../_helpers/src/pepr.ts:25:13)

  console.error
    SyntaxError: Unterminated string in JSON at position 2180 (line 1 column 2181)
        at JSON.parse (<anonymous>)
        at /Users/kas/projects/pepr-excellent-examples/_helpers/src/pepr.ts:14:22
        at Array.map (<anonymous>)
        at sift (/Users/kas/projects/pepr-excellent-examples/_helpers/src/pepr.ts:14:8)
        at logs (/Users/kas/projects/pepr-excellent-examples/_helpers/src/pepr.ts:61:10)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at untilLogged (/Users/kas/projects/pepr-excellent-examples/_helpers/src/pepr.ts:66:18)
        at /Users/kas/projects/pepr-excellent-examples/hello-pepr-finalize/capabilities/finalize.e2e.test.ts:121:9
        at timed (/Users/kas/projects/pepr-excellent-examples/_helpers/src/time.ts:14:3)
        at Object.<anonymous> (/Users/kas/projects/pepr-excellent-examples/hello-pepr-finalize/capabilities/finalize.e2e.test.ts:115:7)

      37 |     }
      38 |     else {
    > 39 |       console.error(e);
         |               ^
      40 |     }
      41 |   }
      42 | }

      at sift (../_helpers/src/pepr.ts:39:15)
      at logs (../_helpers/src/pepr.ts:61:10)
      at untilLogged (../_helpers/src/pepr.ts:66:18)
      at capabilities/finalize.e2e.test.ts:121:9
      at timed (../_helpers/src/time.ts:14:3)
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:115:7)
```
and
```
 FAIL  capabilities/finalize.e2e.test.ts (470.228 s)
  finalize.ts
    create
      ✕ triggers action and finalizer callbacks
    createorupdate
      ✕ triggers action and finalizer callbacks
    update
      ✕ triggers action and finalizer callbacks
    delete
      ✕ triggers action and finalizer callbacks

  ● finalize.ts › create › triggers action and finalizer callbacks

    TypeError: Cannot read properties of undefined (reading 'filter')

      68 |     let found = []
      69 |     if (typeof needle === 'string') {
    > 70 |       found = logz.filter(l => l.includes(needle))
         |                    ^
      71 |     }
      72 |     else if (typeof needle === 'function') {
      73 |       found = logz.filter(l => needle(l))

      at untilLogged (../_helpers/src/pepr.ts:70:20)
      at capabilities/finalize.e2e.test.ts:30:9
      at timed (../_helpers/src/time.ts:14:3)
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:23:7)

  ● finalize.ts › createorupdate › triggers action and finalizer callbacks

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      48 |     let logz: string[]
      49 |
    > 50 |      beforeAll(async () => {
         |               ^
      51 |       const file = `${trc.root()}/capabilities/scenario.create-or-update.yaml`;
      52 |       await timed(`load: ${file}`, async () => {
      53 |         let [ ns, cmWatch ] = await trc.load(file)

      at capabilities/finalize.e2e.test.ts:50:15
      at capabilities/finalize.e2e.test.ts:47:11
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:11:9)

  ● finalize.ts › update › triggers action and finalizer callbacks

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      80 |     let logz: string[]
      81 |
    > 82 |      beforeAll(async () => {
         |               ^
      83 |       const file = `${trc.root()}/capabilities/scenario.update.yaml`;
      84 |       await timed(`load: ${file}`, async () => {
      85 |         let [ ns, cmWatch ] = await trc.load(file)

      at capabilities/finalize.e2e.test.ts:82:15
      at capabilities/finalize.e2e.test.ts:79:11
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:11:9)

  ● finalize.ts › delete › triggers action and finalizer callbacks

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      111 |     let logz: string[]
      112 |
    > 113 |      beforeAll(async () => {
          |               ^
      114 |       const file = `${trc.root()}/capabilities/scenario.delete.yaml`;
      115 |       await timed(`load: ${file}`, async () => {
      116 |         let [ ns, cmWatch ] = await trc.load(file)

      at capabilities/finalize.e2e.test.ts:113:15
      at capabilities/finalize.e2e.test.ts:110:11
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:11:9)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        470.283 s
Ran all test suites matching /.*.e2e.test.ts/i.

node:internal/modules/run_main:115
    triggerUncaughtException(
    ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26924,
  stdout: null,
  stderr: null
}

Node.js v22.2.0
npm error Lifecycle script `_node` failed with error:
npm error Error: command failed
npm error   in workspace: helpers@0.0.0
npm error   at location: /Users/kas/projects/pepr-excellent-examples/_helpers
npm error Lifecycle script `cli` failed with error:
npm error Error: command failed
npm error   in workspace: helpers@0.0.0
npm error   at location: /Users/kas/projects/pepr-excellent-examples/_helpers
npm error Lifecycle script `cli` failed with error:
npm error Error: command failed
npm error   in workspace: hello-pepr-finalize@0.0.1
npm error   at location: /Users/kas/projects/pepr-excellent-examples/hello-pepr-finalize
npm error Lifecycle script `test:e2e` failed with error:
npm error Error: command failed
npm error   in workspace: hello-pepr-finalize@0.0.1
npm error   at location: /Users/kas/projects/pepr-excellent-examples/hello-pepr-finalize
```

**Comment by samayer12** [comment]
Related to https://github.com/defenseunicorns/pepr/issues/1307
